/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spdvi.dialogs;

import java.awt.Color;

/**
 *
 * @author lawde
 */
public class ConfirmDelete extends javax.swing.JDialog {
    private boolean confirm;
    /**
     * Creates new form ConfirmDelete
     */
    public ConfirmDelete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelBotoYes = new javax.swing.JPanel();
        lblTextYes = new javax.swing.JLabel();
        PanelBotoNo = new javax.swing.JPanel();
        lblTextNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel1.setText("Are you sure you want to delete your account?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, -1));

        PanelBotoYes.setBackground(new java.awt.Color(0, 134, 190));

        lblTextYes.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        lblTextYes.setForeground(new java.awt.Color(255, 255, 255));
        lblTextYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextYes.setText("Yes");
        lblTextYes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTextYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTextYesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTextYesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTextYesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBotoYesLayout = new javax.swing.GroupLayout(PanelBotoYes);
        PanelBotoYes.setLayout(PanelBotoYesLayout);
        PanelBotoYesLayout.setHorizontalGroup(
            PanelBotoYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(PanelBotoYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBotoYesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTextYes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelBotoYesLayout.setVerticalGroup(
            PanelBotoYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(PanelBotoYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBotoYesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTextYes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(PanelBotoYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, 20));

        PanelBotoNo.setBackground(new java.awt.Color(0, 134, 190));

        lblTextNo.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        lblTextNo.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextNo.setText("No");
        lblTextNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTextNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTextNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTextNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTextNoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBotoNoLayout = new javax.swing.GroupLayout(PanelBotoNo);
        PanelBotoNo.setLayout(PanelBotoNoLayout);
        PanelBotoNoLayout.setHorizontalGroup(
            PanelBotoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(PanelBotoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBotoNoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTextNo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelBotoNoLayout.setVerticalGroup(
            PanelBotoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(PanelBotoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBotoNoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTextNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(PanelBotoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTextYesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextYesMouseEntered
        PanelBotoYes.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lblTextYesMouseEntered

    private void lblTextYesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextYesMouseExited
        PanelBotoNo.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_lblTextYesMouseExited

    private void lblTextYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextYesMouseClicked
        confirm = true;
        this.setVisible(false);
    }//GEN-LAST:event_lblTextYesMouseClicked

    private void lblTextNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextNoMouseEntered
        PanelBotoNo.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lblTextNoMouseEntered

    private void lblTextNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextNoMouseExited
        PanelBotoNo.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_lblTextNoMouseExited

    private void lblTextNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextNoMouseClicked
        confirm = false;
        this.setVisible(false);
    }//GEN-LAST:event_lblTextNoMouseClicked

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmDelete dialog = new ConfirmDelete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotoNo;
    private javax.swing.JPanel PanelBotoYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTextNo;
    private javax.swing.JLabel lblTextYes;
    // End of variables declaration//GEN-END:variables
}
