/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spdvi.dialogs;

import spdvi.dataaccess.DataAccess;
import com.azure.core.util.Context;
import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobServiceClient;
import com.azure.storage.blob.BlobServiceClientBuilder;
import com.azure.storage.blob.models.BlobItem;
import com.azure.storage.blob.models.BlobRange;
import com.azure.storage.blob.models.DownloadRetryOptions;
import com.azure.storage.blob.specialized.BlockBlobClient;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import spdvi.helpers.ImageHelper;
import spdvi.pojos.Comentari;
import spdvi.pojos.Espai;
import spdvi.pojos.Imatge;
import spdvi.pojos.User;

/**
 *
 * @author angel
 */
public class EspaiDetailsDialog extends javax.swing.JDialog implements Runnable{
    //private ArrayList<String> blobNames = new ArrayList<>();
    private JList<Comentari> lstComents;
    private ArrayList<Imatge> imatges = new ArrayList<>();
    private int contador = 0;
    private Espai selectedEspai;
    private Thread downloadThread;
    private String gif = "resizedloaderBig.gif";
    private User currentUser;
    /**
     * Creates new form Visualitzar
     */
    public EspaiDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lstComents = new JList<Comentari>();
        scrComents.setViewportView(lstComents);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        scrServeis = new javax.swing.JScrollPane();
        txaServeis = new javax.swing.JTextArea();
        scrModalitats = new javax.swing.JScrollPane();
        txaModalitats = new javax.swing.JTextArea();
        pnlContacte = new javax.swing.JPanel();
        lblContacte = new javax.swing.JLabel();
        lblEmailTitle = new javax.swing.JLabel();
        lblWebTitle = new javax.swing.JLabel();
        lblTelefonTitle = new javax.swing.JLabel();
        lblGestorTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblGestor = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        scrEng = new javax.swing.JScrollPane();
        txaEn = new javax.swing.JTextArea();
        scrCat = new javax.swing.JScrollPane();
        txaCat = new javax.swing.JTextArea();
        scrEsp = new javax.swing.JScrollPane();
        txaEsp = new javax.swing.JTextArea();
        lblModalitatsTitle = new javax.swing.JLabel();
        lblTipus = new javax.swing.JLabel();
        lblAdreca = new javax.swing.JLabel();
        lblServeisTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnComentar = new javax.swing.JButton();
        txtComentari = new javax.swing.JTextField();
        lblEn = new javax.swing.JLabel();
        lblEsp = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblDescripcions = new javax.swing.JLabel();
        scrComents = new javax.swing.JScrollPane();
        lblComentaris = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblTitol = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        prgImage = new javax.swing.JProgressBar();
        btnNext = new javax.swing.JButton();
        btnBorrarComentari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 350, 240));

        txaServeis.setEditable(false);
        txaServeis.setColumns(20);
        txaServeis.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txaServeis.setLineWrap(true);
        txaServeis.setRows(5);
        txaServeis.setWrapStyleWord(true);
        scrServeis.setViewportView(txaServeis);

        jPanel1.add(scrServeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, 80));

        txaModalitats.setEditable(false);
        txaModalitats.setColumns(20);
        txaModalitats.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txaModalitats.setLineWrap(true);
        txaModalitats.setRows(5);
        txaModalitats.setWrapStyleWord(true);
        scrModalitats.setViewportView(txaModalitats);

        jPanel1.add(scrModalitats, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 80));

        pnlContacte.setBackground(new java.awt.Color(255, 255, 255));

        lblContacte.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblContacte.setText("Contacte");

        lblEmailTitle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEmailTitle.setText("Email: ");

        lblWebTitle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblWebTitle.setText("Web: ");

        lblTelefonTitle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblTelefonTitle.setText("Telefon: ");

        lblGestorTitle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblGestorTitle.setText("Gestor: ");

        lblEmail.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEmail.setText("email");

        lblGestor.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblGestor.setText("gestor");

        lblTelefon.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblTelefon.setText("telefon");

        lblWeb.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblWeb.setText("web");

        javax.swing.GroupLayout pnlContacteLayout = new javax.swing.GroupLayout(pnlContacte);
        pnlContacte.setLayout(pnlContacteLayout);
        pnlContacteLayout.setHorizontalGroup(
            pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContacteLayout.createSequentialGroup()
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlContacteLayout.createSequentialGroup()
                            .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTelefonTitle)
                                .addComponent(lblWebTitle))
                            .addGap(18, 18, Short.MAX_VALUE))
                        .addGroup(pnlContacteLayout.createSequentialGroup()
                            .addComponent(lblGestorTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(1, 1, 1)))
                    .addGroup(pnlContacteLayout.createSequentialGroup()
                        .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContacte)
                            .addComponent(lblEmailTitle))
                        .addGap(21, 21, 21)))
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblWeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelefon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContacteLayout.setVerticalGroup(
            pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContacteLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblContacte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTitle)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonTitle)
                    .addComponent(lblTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebTitle)
                    .addComponent(lblWeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestorTitle)
                    .addComponent(lblGestor))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(pnlContacte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, -1));

        scrEng.setMaximumSize(new java.awt.Dimension(226, 86));
        scrEng.setMinimumSize(new java.awt.Dimension(226, 86));

        txaEn.setEditable(false);
        txaEn.setColumns(20);
        txaEn.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txaEn.setLineWrap(true);
        txaEn.setRows(5);
        txaEn.setWrapStyleWord(true);
        txaEn.setMaximumSize(new java.awt.Dimension(224, 84));
        txaEn.setMinimumSize(new java.awt.Dimension(224, 84));
        scrEng.setViewportView(txaEn);

        jPanel1.add(scrEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        txaCat.setEditable(false);
        txaCat.setColumns(20);
        txaCat.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txaCat.setLineWrap(true);
        txaCat.setRows(5);
        txaCat.setWrapStyleWord(true);
        txaCat.setMaximumSize(new java.awt.Dimension(224, 84));
        txaCat.setMinimumSize(new java.awt.Dimension(224, 84));
        scrCat.setViewportView(txaCat);

        jPanel1.add(scrCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txaEsp.setEditable(false);
        txaEsp.setColumns(20);
        txaEsp.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txaEsp.setLineWrap(true);
        txaEsp.setRows(5);
        txaEsp.setWrapStyleWord(true);
        txaEsp.setMaximumSize(new java.awt.Dimension(224, 84));
        txaEsp.setMinimumSize(new java.awt.Dimension(224, 84));
        scrEsp.setViewportView(txaEsp);

        jPanel1.add(scrEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        lblModalitatsTitle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblModalitatsTitle.setText("Modalitats: ");
        jPanel1.add(lblModalitatsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 90, -1));

        lblTipus.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblTipus.setText("Tipus");
        jPanel1.add(lblTipus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        lblAdreca.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblAdreca.setText("Adreça");
        jPanel1.add(lblAdreca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 940, -1, -1));

        lblServeisTitle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblServeisTitle.setText("Serveis:");
        jPanel1.add(lblServeisTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 60, -1));

        lblUser.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUser.setText("Usuari:");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 890, 100, 30));

        btnComentar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnComentar.setText("Comentar");
        btnComentar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComentarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComentarMouseExited(evt);
            }
        });
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 890, 110, 30));

        txtComentari.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtComentari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentariActionPerformed(evt);
            }
        });
        txtComentari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComentariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComentariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComentariKeyTyped(evt);
            }
        });
        jPanel1.add(txtComentari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, 570, 30));

        lblEn.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEn.setText("English");
        jPanel1.add(lblEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        lblEsp.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEsp.setText("Español");
        jPanel1.add(lblEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        lblCat.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCat.setText("Català");
        jPanel1.add(lblCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblDescripcions.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblDescripcions.setText("Descripcions: ");
        jPanel1.add(lblDescripcions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        scrComents.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(scrComents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 800, 150));

        lblComentaris.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblComentaris.setText("Comentaris");
        jPanel1.add(lblComentaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 140, -1));

        lblRegister.setBackground(new java.awt.Color(0, 0, 0));
        lblRegister.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblRegister.setText("Registre");
        jPanel1.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        lblTitol.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblTitol.setText("Titol");
        jPanel1.add(lblTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 790, -1));

        btnPrevious.setBackground(new java.awt.Color(255, 255, 255));
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.png"))); // NOI18N
        btnPrevious.setBorder(null);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        prgImage.setBackground(new java.awt.Color(255, 255, 255));
        prgImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        prgImage.setStringPainted(true);
        jPanel1.add(prgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 220, 30));

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        btnBorrarComentari.setFont(btnComentar.getFont());
        btnBorrarComentari.setText("Borrar");
        btnBorrarComentari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarComentariActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarComentari, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 930, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        lblImage.setIcon(new ImageIcon(EspaiDetailsDialog.class.getClassLoader().getResource(gif)));
        contador++;
        if(contador == imatges.size() - 1){
            btnNext.setEnabled(false);
        }
        btnPrevious.setEnabled(true);
        downloadThread = new Thread(this);
        downloadThread.start();
    }//GEN-LAST:event_btnNextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DataAccess da = new DataAccess();
        lblImage.setIcon(new ImageIcon(EspaiDetailsDialog.class.getClassLoader().getResource(gif)));
        btnPrevious.setEnabled(false);
        btnComentar.setEnabled(false);
 
        updateComentarisView(da);

        imatges = da.getImatgesEspai(selectedEspai);
        if(imatges.size() == 1){
            btnNext.setEnabled(false);
        }
        downloadThread = new Thread(this);
        downloadThread.start();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        lblImage.setIcon(new ImageIcon(EspaiDetailsDialog.class.getClassLoader().getResource(gif)));
        contador--;
        if(contador == 0){
            btnPrevious.setEnabled(false);
        }
        btnNext.setEnabled(true);
        downloadThread = new Thread(this);
        downloadThread.start();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void txtComentariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComentariActionPerformed

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        Comentari comentari = new Comentari(currentUser.getEmail(), selectedEspai.getRegistre(), txtComentari.getText(), LocalDate.now(), LocalTime.now(), currentUser.getUserName());
        DataAccess da = new DataAccess();
        da.insertComentari(comentari);
        updateComentarisView(da);
        txtComentari.setText("");
        btnComentar.setEnabled(false);
    }//GEN-LAST:event_btnComentarActionPerformed

    private void txtComentariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentariKeyPressed
        
    }//GEN-LAST:event_txtComentariKeyPressed

    private void txtComentariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentariKeyTyped
        
    }//GEN-LAST:event_txtComentariKeyTyped

    private void txtComentariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentariKeyReleased
        if(txtComentari.getText() == null || txtComentari.getText().isBlank() || txtComentari.getText().isEmpty()){
           btnComentar.setEnabled(false);
        }else{
            btnComentar.setEnabled(true);
        }
    }//GEN-LAST:event_txtComentariKeyReleased

    private void btnComentarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComentarMouseEntered
       
    }//GEN-LAST:event_btnComentarMouseEntered

    private void btnComentarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComentarMouseExited
       
    }//GEN-LAST:event_btnComentarMouseExited

    private void btnBorrarComentariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarComentariActionPerformed
        if(lstComents.getSelectedValue() != null){
            //lstComents.remove(lstComents.getSelectedIndex());
            DataAccess da = new DataAccess();
            da.deleteComentari(lstComents.getSelectedValue());
            updateComentarisView(da);
        }
    }//GEN-LAST:event_btnBorrarComentariActionPerformed

    @Override
    public void run() {
        System.out.println(Thread.currentThread().getName());
        ImageHelper.downloadImage(lblImage, prgImage, imatges.get(contador).getImatge());
        //downloadImage();
    }

    private void updateComentarisView(DataAccess da){
        DefaultListModel<Comentari> defaultListModel = new DefaultListModel<>();
        for(Comentari co: da.getComentaris(selectedEspai)){
            defaultListModel.addElement(co);
        }
        lstComents.setModel(defaultListModel);
    }
    public Espai getSelectedEspai() {
        return selectedEspai;
    }

    public void setSelectedEspai(Espai selectedEspai) {
        this.selectedEspai = selectedEspai;
    }

    public JLabel getLblComentaris() {
        return lblComentaris;
    }

    public void setLblComentaris(JLabel lblComentaris) {
        this.lblComentaris = lblComentaris;
    }

    public JLabel getLblRegister() {
        return lblRegister;
    }

    public void setLblRegister(JLabel lblRegister) {
        this.lblRegister = lblRegister;
    }

    public JLabel getLblTitol() {
        return lblTitol;
    }

    public void setLblTitol(JLabel lblTitol) {
        this.lblTitol = lblTitol;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }
    
    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }

    public JLabel getLblAdreca() {
        return lblAdreca;
    }

    public void setLblAdreca(JLabel lblAdreca) {
        this.lblAdreca = lblAdreca;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }

    public JLabel getLblGestor() {
        return lblGestor;
    }

    public void setLblGestor(JLabel lblGestor) {
        this.lblGestor = lblGestor;
    }

    public JLabel getLblWeb() {
        return lblWeb;
    }

    public void setLblWeb(JLabel lblWeb) {
        this.lblWeb = lblWeb;
    }

    public JLabel getLblTelefon() {
        return lblTelefon;
    }

    public void setLblTelefon(JLabel lblTelefon) {
        this.lblTelefon = lblTelefon;
    }

    public JTextArea getTxaServeis() {
        return txaServeis;
    }

    public void setTxaServeis(JTextArea txaServeis) {
        this.txaServeis = txaServeis;
    }

    public JTextArea getTxaModalitats() {
        return txaModalitats;
    }

    public void setTxaModalitats(JTextArea txaModalitats) {
        this.txaModalitats = txaModalitats;
    }

    public JLabel getLblTipus() {
        return lblTipus;
    }

    public void setLblTipus(JLabel lblTipus) {
        this.lblTipus = lblTipus;
    }

    public JTextArea getTxaCat() {
        return txaCat;
    }

    public void setTxaCat(JTextArea txaCat) {
        this.txaCat = txaCat;
    }

    public JTextArea getTxaEn() {
        return txaEn;
    }

    public void setTxaEn(JTextArea txaEn) {
        this.txaEn = txaEn;
    }

    public JTextArea getTxaEsp() {
        return txaEsp;
    }

    public void setTxaEsp(JTextArea txaEsp) {
        this.txaEsp = txaEsp;
    }

    public JButton getBtnBorrarComentari() {
        return btnBorrarComentari;
    }

    public void setBtnBorrarComentari(JButton btnBorrarComentari) {
        this.btnBorrarComentari = btnBorrarComentari;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EspaiDetailsDialog dialog = new EspaiDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarComentari;
    private javax.swing.JButton btnComentar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdreca;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblComentaris;
    private javax.swing.JLabel lblContacte;
    private javax.swing.JLabel lblDescripcions;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailTitle;
    private javax.swing.JLabel lblEn;
    private javax.swing.JLabel lblEsp;
    private javax.swing.JLabel lblGestor;
    private javax.swing.JLabel lblGestorTitle;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblModalitatsTitle;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblServeisTitle;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonTitle;
    private javax.swing.JLabel lblTipus;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JLabel lblWebTitle;
    private javax.swing.JPanel pnlContacte;
    private javax.swing.JProgressBar prgImage;
    private javax.swing.JScrollPane scrCat;
    private javax.swing.JScrollPane scrComents;
    private javax.swing.JScrollPane scrEng;
    private javax.swing.JScrollPane scrEsp;
    private javax.swing.JScrollPane scrModalitats;
    private javax.swing.JScrollPane scrServeis;
    private javax.swing.JTextArea txaCat;
    private javax.swing.JTextArea txaEn;
    private javax.swing.JTextArea txaEsp;
    private javax.swing.JTextArea txaModalitats;
    private javax.swing.JTextArea txaServeis;
    private javax.swing.JTextField txtComentari;
    // End of variables declaration//GEN-END:variables
}
