/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spdvi.dialogs;

import spdvi.helpers.DataAccess;
import com.azure.core.util.Context;
import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobServiceClient;
import com.azure.storage.blob.BlobServiceClientBuilder;
import com.azure.storage.blob.models.BlobItem;
import com.azure.storage.blob.models.BlobRange;
import com.azure.storage.blob.models.DownloadRetryOptions;
import com.azure.storage.blob.specialized.BlockBlobClient;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import spdvi.helpers.ImageHelper;
import spdvi.pojos.Comentari;
import spdvi.pojos.Espai;
import spdvi.pojos.Imatge;
import spdvi.pojos.User;

/**
 *
 * @author angel
 */
public class Visualitzar extends javax.swing.JDialog implements Runnable{
    //private ArrayList<String> blobNames = new ArrayList<>();
    private JList<Comentari> lstComents;
    private ArrayList<Imatge> imatges = new ArrayList<>();
    private int contador = 0;
    private Espai selectedEspai;
    private Thread downloadThread;
    private String gif = "resizedloaderBig.gif";
    private User currentUser;
    /**
     * Creates new form Visualitzar
     */
    public Visualitzar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lstComents = new JList<Comentari>();
        scrComents.setViewportView(lstComents);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        prgImage = new javax.swing.JProgressBar();
        btnPrevious = new javax.swing.JButton();
        lblTitol = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblComentaris = new javax.swing.JLabel();
        scrComents = new javax.swing.JScrollPane();
        lblDescripcions = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblEsp = new javax.swing.JLabel();
        lblEn = new javax.swing.JLabel();
        txtComentari = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lblServeisTitle = new javax.swing.JLabel();
        lblAdreca = new javax.swing.JLabel();
        lblTipus = new javax.swing.JLabel();
        lblModalitatsTitle = new javax.swing.JLabel();
        scrEsp = new javax.swing.JScrollPane();
        txaEsp = new javax.swing.JTextArea();
        scrCat = new javax.swing.JScrollPane();
        txaCat = new javax.swing.JTextArea();
        scrEng = new javax.swing.JScrollPane();
        txaEn = new javax.swing.JTextArea();
        pnlContacte = new javax.swing.JPanel();
        lblContacte = new javax.swing.JLabel();
        lblEmailTitle = new javax.swing.JLabel();
        lblWebTitle = new javax.swing.JLabel();
        lblTelefonTitle = new javax.swing.JLabel();
        lblGestorTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        lblGestor = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        scrModalitats = new javax.swing.JScrollPane();
        txaModalitats = new javax.swing.JTextArea();
        scrServeis = new javax.swing.JScrollPane();
        txaServeis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.setMaximumSize(new java.awt.Dimension(80, 80));
        btnNext.setPreferredSize(new java.awt.Dimension(80, 80));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        prgImage.setStringPainted(true);

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.png"))); // NOI18N
        btnPrevious.setBorder(null);
        btnPrevious.setMaximumSize(new java.awt.Dimension(80, 80));
        btnPrevious.setPreferredSize(new java.awt.Dimension(80, 80));
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblTitol.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTitol.setText("Titol");

        lblRegister.setText("Registre");

        lblComentaris.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblComentaris.setText("Comentaris");

        lblDescripcions.setText("Descripcions: ");

        lblCat.setText("Català");

        lblEsp.setText("Español");

        lblEn.setText("English");

        txtComentari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentariActionPerformed(evt);
            }
        });
        txtComentari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComentariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComentariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComentariKeyTyped(evt);
            }
        });

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        lblUser.setText("Usuari:");

        lblServeisTitle.setText("Serveis:");

        lblAdreca.setText("Adreça");

        lblTipus.setText("Tipus");

        lblModalitatsTitle.setText("Modalitats: ");

        txaEsp.setEditable(false);
        txaEsp.setColumns(20);
        txaEsp.setLineWrap(true);
        txaEsp.setRows(5);
        txaEsp.setWrapStyleWord(true);
        scrEsp.setViewportView(txaEsp);

        txaCat.setEditable(false);
        txaCat.setColumns(20);
        txaCat.setLineWrap(true);
        txaCat.setRows(5);
        txaCat.setWrapStyleWord(true);
        txaCat.setMaximumSize(new java.awt.Dimension(164, 94));
        txaCat.setMinimumSize(new java.awt.Dimension(164, 94));
        scrCat.setViewportView(txaCat);

        txaEn.setEditable(false);
        txaEn.setColumns(20);
        txaEn.setLineWrap(true);
        txaEn.setRows(5);
        txaEn.setWrapStyleWord(true);
        scrEng.setViewportView(txaEn);

        lblContacte.setText("Contacte");

        lblEmailTitle.setText("Email: ");

        lblWebTitle.setText("Web: ");

        lblTelefonTitle.setText("Telefon: ");

        lblGestorTitle.setText("Gestor: ");

        lblEmail.setText("email");

        lblWeb.setText("web");

        lblGestor.setText("gestor");

        lblTelefon.setText("telefon");

        javax.swing.GroupLayout pnlContacteLayout = new javax.swing.GroupLayout(pnlContacte);
        pnlContacte.setLayout(pnlContacteLayout);
        pnlContacteLayout.setHorizontalGroup(
            pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContacteLayout.createSequentialGroup()
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContacteLayout.createSequentialGroup()
                        .addComponent(lblGestorTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContacteLayout.createSequentialGroup()
                            .addComponent(lblEmailTitle)
                            .addGap(18, 18, 18)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlContacteLayout.createSequentialGroup()
                            .addComponent(lblTelefonTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContacteLayout.createSequentialGroup()
                            .addComponent(lblWebTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblContacte))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        pnlContacteLayout.setVerticalGroup(
            pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContacteLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblContacte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTitle)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonTitle)
                    .addComponent(lblTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebTitle)
                    .addComponent(lblWeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestorTitle)
                    .addComponent(lblGestor))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        txaModalitats.setEditable(false);
        txaModalitats.setColumns(20);
        txaModalitats.setLineWrap(true);
        txaModalitats.setRows(5);
        txaModalitats.setWrapStyleWord(true);
        scrModalitats.setViewportView(txaModalitats);

        txaServeis.setEditable(false);
        txaServeis.setColumns(20);
        txaServeis.setLineWrap(true);
        txaServeis.setRows(5);
        txaServeis.setWrapStyleWord(true);
        scrServeis.setViewportView(txaServeis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComentaris)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescripcions)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtComentari, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnComentar))
                                        .addComponent(scrComents, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEn)
                                    .addComponent(scrEng, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrServeis, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlContacte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModalitatsTitle)
                                    .addComponent(lblServeisTitle)
                                    .addComponent(scrModalitats, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipus)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrCat, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCat))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEsp)))
                            .addComponent(lblRegister)
                            .addComponent(lblTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblTipus)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcions)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEsp)
                        .addComponent(lblCat))
                    .addComponent(lblEn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrEsp)
                    .addComponent(scrEng)
                    .addComponent(scrCat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlContacte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModalitatsTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrModalitats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblServeisTitle))
                            .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrServeis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(lblComentaris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prgImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)))))
                .addComponent(scrComents, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUser))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtComentari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnComentar)))
                .addGap(18, 18, 18)
                .addComponent(lblAdreca)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        lblImage.setIcon(new ImageIcon(Visualitzar.class.getClassLoader().getResource(gif)));
        contador++;
        if(contador == imatges.size() - 1){
            btnNext.setEnabled(false);
        }
        btnPrevious.setEnabled(true);
        downloadThread = new Thread(this);
        downloadThread.start();
    }//GEN-LAST:event_btnNextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DataAccess da = new DataAccess();
        lblImage.setIcon(new ImageIcon(Visualitzar.class.getClassLoader().getResource(gif)));
        btnPrevious.setEnabled(false);
        btnComentar.setEnabled(false);
 
        updateComentarisView(da);

        imatges = da.getImatgesEspai(selectedEspai);
        if(imatges.size() == 1){
            btnNext.setEnabled(false);
        }
        downloadThread = new Thread(this);
        downloadThread.start();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        lblImage.setIcon(new ImageIcon(Visualitzar.class.getClassLoader().getResource(gif)));
        contador--;
        if(contador == 0){
            btnPrevious.setEnabled(false);
        }
        btnNext.setEnabled(true);
        downloadThread = new Thread(this);
        downloadThread.start();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void txtComentariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComentariActionPerformed

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        Comentari comentari = new Comentari(currentUser.getEmail(), selectedEspai.getRegistre(), txtComentari.getText(), LocalDate.now(), LocalTime.now(), currentUser.getUserName());
        DataAccess da = new DataAccess();
        da.insertComentari(comentari);
        updateComentarisView(da);
        txtComentari.setText("");
        btnComentar.setEnabled(false);
    }//GEN-LAST:event_btnComentarActionPerformed

    private void txtComentariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentariKeyPressed
        
    }//GEN-LAST:event_txtComentariKeyPressed

    private void txtComentariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentariKeyTyped
        
    }//GEN-LAST:event_txtComentariKeyTyped

    private void txtComentariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentariKeyReleased
        if(txtComentari.getText() == null || txtComentari.getText().isBlank() || txtComentari.getText().isEmpty()){
           btnComentar.setEnabled(false);
        }else{
            btnComentar.setEnabled(true);
        }
    }//GEN-LAST:event_txtComentariKeyReleased

    @Override
    public void run() {
        System.out.println(Thread.currentThread().getName());
        ImageHelper.downloadImage(lblImage, prgImage, imatges.get(contador).getImatge());
        //downloadImage();
    }

    private void updateComentarisView(DataAccess da){
        DefaultListModel<Comentari> defaultListModel = new DefaultListModel<>();
        for(Comentari co: da.getComentaris(selectedEspai)){
            defaultListModel.addElement(co);
        }
        lstComents.setModel(defaultListModel);
    }
    public Espai getSelectedEspai() {
        return selectedEspai;
    }

    public void setSelectedEspai(Espai selectedEspai) {
        this.selectedEspai = selectedEspai;
    }

    public JLabel getLblComentaris() {
        return lblComentaris;
    }

    public void setLblComentaris(JLabel lblComentaris) {
        this.lblComentaris = lblComentaris;
    }

    public JLabel getLblRegister() {
        return lblRegister;
    }

    public void setLblRegister(JLabel lblRegister) {
        this.lblRegister = lblRegister;
    }

    public JLabel getLblTitol() {
        return lblTitol;
    }

    public void setLblTitol(JLabel lblTitol) {
        this.lblTitol = lblTitol;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }
    
    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }

    public JLabel getLblAdreca() {
        return lblAdreca;
    }

    public void setLblAdreca(JLabel lblAdreca) {
        this.lblAdreca = lblAdreca;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }

    public JLabel getLblGestor() {
        return lblGestor;
    }

    public void setLblGestor(JLabel lblGestor) {
        this.lblGestor = lblGestor;
    }

    public JLabel getLblWeb() {
        return lblWeb;
    }

    public void setLblWeb(JLabel lblWeb) {
        this.lblWeb = lblWeb;
    }

    public JLabel getLblTelefon() {
        return lblTelefon;
    }

    public void setLblTelefon(JLabel lblTelefon) {
        this.lblTelefon = lblTelefon;
    }

    public JTextArea getTxaServeis() {
        return txaServeis;
    }

    public void setTxaServeis(JTextArea txaServeis) {
        this.txaServeis = txaServeis;
    }

    public JTextArea getTxaModalitats() {
        return txaModalitats;
    }

    public void setTxaModalitats(JTextArea txaModalitats) {
        this.txaModalitats = txaModalitats;
    }

    public JLabel getLblTipus() {
        return lblTipus;
    }

    public void setLblTipus(JLabel lblTipus) {
        this.lblTipus = lblTipus;
    }

    public JTextArea getTxaCat() {
        return txaCat;
    }

    public void setTxaCat(JTextArea txaCat) {
        this.txaCat = txaCat;
    }

    public JTextArea getTxaEn() {
        return txaEn;
    }

    public void setTxaEn(JTextArea txaEn) {
        this.txaEn = txaEn;
    }

    public JTextArea getTxaEsp() {
        return txaEsp;
    }

    public void setTxaEsp(JTextArea txaEsp) {
        this.txaEsp = txaEsp;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualitzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualitzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualitzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualitzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Visualitzar dialog = new Visualitzar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel lblAdreca;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblComentaris;
    private javax.swing.JLabel lblContacte;
    private javax.swing.JLabel lblDescripcions;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailTitle;
    private javax.swing.JLabel lblEn;
    private javax.swing.JLabel lblEsp;
    private javax.swing.JLabel lblGestor;
    private javax.swing.JLabel lblGestorTitle;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblModalitatsTitle;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblServeisTitle;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonTitle;
    private javax.swing.JLabel lblTipus;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JLabel lblWebTitle;
    private javax.swing.JPanel pnlContacte;
    private javax.swing.JProgressBar prgImage;
    private javax.swing.JScrollPane scrCat;
    private javax.swing.JScrollPane scrComents;
    private javax.swing.JScrollPane scrEng;
    private javax.swing.JScrollPane scrEsp;
    private javax.swing.JScrollPane scrModalitats;
    private javax.swing.JScrollPane scrServeis;
    private javax.swing.JTextArea txaCat;
    private javax.swing.JTextArea txaEn;
    private javax.swing.JTextArea txaEsp;
    private javax.swing.JTextArea txaModalitats;
    private javax.swing.JTextArea txaServeis;
    private javax.swing.JTextField txtComentari;
    // End of variables declaration//GEN-END:variables
}
